# Generated by Django 2.2.2 on 2020-10-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostador',
            name='saldo',
            field=models.FloatField(default=10.0),
        ),
    ]
