# Generated by Django 2.2.2 on 2020-10-18 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20201018_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_gols_desafiante_apostado', models.PositiveSmallIntegerField()),
                ('qtd_gols_visitante_apostado', models.PositiveSmallIntegerField()),
                ('valor_da_aposta', models.FloatField(default=5.0)),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_selecao', models.CharField(max_length=200)),
                ('qtd_de_titulos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_visitante', models.PositiveSmallIntegerField()),
                ('gols_desafiante', models.PositiveSmallIntegerField()),
                ('data_hora', models.DateTimeField()),
                ('estadio', models.CharField(max_length=200)),
                ('selecao_desafiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecaodesafiante', to='sistema.Selecao')),
                ('selecao_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecaovisitante', to='sistema.Selecao')),
            ],
        ),
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_bolao', models.CharField(max_length=200)),
                ('premiacao', models.FloatField()),
                ('valor_disputado', models.FloatField()),
                ('apostas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Aposta')),
                ('vencedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aposta',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Partida'),
        ),
    ]
