# Generated by Django 2.2.16 on 2020-10-07 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placarCasa', models.IntegerField()),
                ('placarVisitante', models.IntegerField()),
                ('vencedorPartida', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timeCasa', models.CharField(max_length=30)),
                ('timeVisitante', models.CharField(max_length=30)),
                ('dataPartida', models.DateTimeField(blank=True, null=True)),
                ('jogo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolao.Jogo')),
            ],
        ),
    ]
