# Generated by Django 2.2.16 on 2020-10-07 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='jogo',
        ),
        migrations.AddField(
            model_name='jogo',
            name='partida',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolao.Partida'),
        ),
    ]
