# Generated by Django 2.2.16 on 2020-10-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0002_auto_20201006_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jogo',
            new_name='Resultado',
        ),
    ]
