# Generated by Django 2.2.16 on 2020-10-08 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bolao', '0003_auto_20201006_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='partidaRealizada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Apostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aposta_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_aposta', models.FloatField(verbose_name=5.0)),
                ('aposta_placar_casa', models.IntegerField()),
                ('aposta_placar_vistante', models.IntegerField()),
                ('aposta_vencedor', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apostador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.FloatField(default=10.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
