# Generated by Django 2.2.16 on 2020-10-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_auto_20201007_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='iconTimeCasa',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='iconTimeVisitante',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
