# Generated by Django 2.2.16 on 2020-10-19 02:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bolao', '0005_auto_20201017_0209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apostador',
            new_name='Profile',
        ),
    ]
