# Generated by Django 2.2.16 on 2020-10-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0006_auto_20201018_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apostou',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apostas',
            name='valor_aposta',
            field=models.FloatField(default=5.0),
        ),
    ]
