# Generated by Django 2.2.16 on 2020-10-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0007_auto_20201019_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.IntegerField(default=0),
        ),
    ]
