# Generated by Django 2.2.16 on 2020-10-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0009_partida_permitiraposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField()),
                ('permitirApostas', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='partida',
            name='permitirAposta',
        ),
        migrations.AlterField(
            model_name='partida',
            name='rodada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.Rodada'),
        ),
    ]
