# Generated by Django 2.2.16 on 2020-10-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0010_auto_20201019_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='rodada',
            field=models.IntegerField(null=True),
        ),
    ]
