# Generated by Django 2.2.16 on 2020-10-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0011_auto_20201020_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='rodada',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='partida',
        ),
    ]
