# Generated by Django 2.2.16 on 2020-10-20 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0012_auto_20201020_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='rodada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bolao.Rodada'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='partida',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolao.Partida'),
        ),
    ]
