# Generated by Django 2.2.16 on 2020-10-22 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0013_auto_20201020_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('brasao', models.CharField(max_length=255, verbose_name='brasao')),
            ],
        ),
        migrations.AddField(
            model_name='apostas',
            name='partida',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bolao.Partida'),
        ),
        migrations.AddField(
            model_name='partida',
            name='premiacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partida',
            name='premiacaoDistribuida',
            field=models.BooleanField(default=False),
        ),
    ]
