# Generated by Django 2.2.16 on 2020-10-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0014_auto_20201021_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
