# Generated by Django 2.2.2 on 2020-10-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selecao_um', models.CharField(choices=[('BRA', 'Brasil'), ('ARG', 'Argentina'), ('RUS', 'Rússia'), ('NGA', 'Nigéria'), ('SEN', 'Senegal'), ('GBR', 'Reino Unido')], max_length=40)),
                ('selecao_dois', models.CharField(choices=[('BRA', 'Brasil'), ('ARG', 'Argentina'), ('RUS', 'Rússia'), ('NGA', 'Nigéria'), ('SEN', 'Senegal'), ('GBR', 'Reino Unido')], max_length=40)),
                ('gols_selecao_um', models.PositiveSmallIntegerField()),
                ('gols_selecao_dois', models.PositiveSmallIntegerField()),
                ('resultado_partida', models.CharField(choices=[('BRA', 'Brasil'), ('ARG', 'Argentina'), ('RUS', 'Rússia'), ('NGA', 'Nigéria'), ('SEN', 'Senegal'), ('GBR', 'Reino Unido')], max_length=40)),
            ],
        ),
    ]
